Los 2 ejercicios de netflix
tijanidian/PMDM-TIJANI pull request #2
Opened 2021-10-14 15:30 UTC by tijanidian

Unión de la rama ut03_netflix1 con los dos ejercicios

2021-10-14 15:47 UTC, ghost commented
¿puedes añadirme como revisor? @tijanidian

2021-10-17 13:44 UTC, ghost requested changes
Hola, 
Hay varios cambios que debemos corregir antes de dar la PR como válida. Los cambios se repite: uso de dimen, de string, naminga de los id de las vistas...

Me queda la duda de ver si has maquetado usando paddings o márgenes...

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:text="Auto Descarga"
Acuerdate de usar los recursos de @string. No debemos meter textos a manos al menos que sea en tools:text=""

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:text="Activada"
Acuerdate de usar los recursos de @string. No debemos meter textos a manos al menos que sea en tools:text=""

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:layout_below="@id/Relative_view_1">
El naming de este elemento deberia estar todo en minúsculas ;)

```suggestion
        android:layout_below="@id/view_1">
```

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_3"
El naming de este elemento deberia estar todo en minúsculas ;)
```suggestion
        android:id="@+id/view_3"
```

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_marginLeft="16dp"
Deberias usar dimensiones, @dimen....

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:paddingTop="25dp"
acuerdate de usar @dimens

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:padding="10dp">
Acuerdate de usar @dimen

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_width="22dp"
Cambia estos valores por estilos ;)

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +                android:paddingLeft="10dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_1"
El naming del id debwria ser todo en minusculas.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_marginLeft="16dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_2"
El naming del id debe ser todo en minusculas.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:paddingTop="25dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_marginLeft="16dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:paddingTop="25dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_4"
El naming del id deberia estar en minúsculas.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_marginLeft="16dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:paddingLeft="10dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:paddingTop="10dp">
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_width="48dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_height="48dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingLeft="30dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Programas"
No deberiamos meter texto sin usar @string

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingStart="30dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Películas"
No deberiamos meter textos a mano.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingTop="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingLeft="10dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:id="@+id/Relative_view_3"
El naming del id deberia ser en minúsculas.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingLeft="10dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingTop="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:layout_marginStart="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Populares en Netflix"
Recuerda que no debemos meter textos sin usar @string

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingTop="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingLeft="15dp"
Acuerdate de usar dimens en vez de valores fijos.

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Mi lista"
Recuerdo que para los textos debemos usar @string

2021-10-17 13:44 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingStart="30dp"
Acuerdate de usar dimens en vez de valores fijos. ¿No es mucho padding?

2021-10-20 14:53 UTC, ghost requested changes
Hola Tijani,
Please, check all my comments

2021-10-20 14:53 UTC, ghost commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:padding="10dp">
Mejor usar dimen en vez de valor fijo.

2021-10-20 14:53 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_width="22dp"
mejor usar dimen en vez de un valor fijo

2021-10-21 15:00 UTC, jmperezra requested changes
Intenta hacer lo que hemos hablado y cualquier duda me preguntas ;) 
Va la cosa bien :)

2021-10-21 15:00 UTC, ghost commented on app/src/main/res/values/styles.xml
> +    <style name="IconView_top">
En los estilos se hacen con CamelCase, sin underscore ;)

2021-10-28 14:51 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:text="Auto Descarga"
done

2021-10-28 14:52 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:text="Activada"
done

2021-10-28 14:52 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:layout_below="@id/Relative_view_1">
done

2021-10-28 14:52 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_marginLeft="16dp"
done

2021-10-28 14:53 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Populares en Netflix"
done

2021-10-28 14:53 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingLeft="15dp"
done

2021-10-28 14:54 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:text="Mi lista"
done

2021-10-28 14:54 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingStart="30dp"
done

2021-10-28 14:54 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:padding="10dp">
done

2021-10-28 14:55 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:layout_width="22dp"
done

2021-10-28 14:55 UTC, tijanidian commented on app/src/main/res/values/styles.xml
> +    <style name="IconView_top">
done

2021-10-28 14:56 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_3"
done

2021-10-28 14:56 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +            android:paddingTop="15dp"
done

2021-10-29 18:28 UTC, jmperezra approved these changes
La PR está aprobada pero hay que trabajar mucho con los nombre de los elementos. Tienes que ser descriptivos por si mismos, independiente del resto.

2021-11-11 15:52 UTC, merged