Clone de la aplicación de Glovo de la empresa de McDonald's
tijanidian/PMDM-TIJANI pull request #4
Opened 2021-10-22 18:24 UTC by tijanidian

## Description

Clone de la aplicación de Glovo de la empresa de McDonald's hecha con RelativeLayout
## Related Issue

Not yeat
## How has this been tested?

Not yeat
## Design UI

Not yeat
## Screenshots or Video
![original_img](https://user-images.githubusercontent.com/73607974/138504501-695b2cad-5a4a-4371-9040-0cd54a8e9b2c.PNG)

![clone_glovo](https://user-images.githubusercontent.com/73607974/138504609-8204b4a9-dcce-4f79-a499-810e88a8a8d6.PNG)

2021-10-29 18:34 UTC, jmperezra requested changes
El código necesita una revisión profunda de namings.

2021-10-29 18:34 UTC, jmperezra commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:src="@mipmap/glovo_comida" />
Las imágenes deben ir en las carpetas de drawable-xxxxxxx donde xxxxx puede ser xhdpi, xxhdpi, hdpi, etc.

2021-10-29 18:34 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_2"
Revisa los namings.

2021-10-29 18:34 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_1"
Revisa los namings.

2021-10-29 18:34 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_3"
Revisa los namings.

2021-10-29 18:34 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_4"
Revisa los namings.

2021-11-02 09:49 UTC, tijanidian commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:src="@mipmap/glovo_comida" />
done

2021-11-02 09:49 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_2"
done

2021-11-02 10:20 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_1"
done

2021-11-02 10:20 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_3"
done

2021-11-02 10:20 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_4"
done

2021-11-11 15:59 UTC, jmperezra approved these changes
Tijani, hay unos errores de namings. Puedes cambiarlos o dejarlos así  para seguir a la par con la clase, pero en próximas PR no serán aceptados,

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:id="@+id/appCompatImageView"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:id="@+id/main_text"
Hay que fijarse en el nombre de los id: su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:id="@+id/secundary_text"
Hay que fijarse en el nombre de los id: su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:id="@+id/img3"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +                android:id="@+id/img4"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_2"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_1"
¿Tienes subidos todos los cambios?

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_2"
¿tienes subidos todos los cambios?

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:id="@+id/img_button5"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.
Y así con todos los img_button4 :(

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:id="@+id/Relative_view_1"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-11 15:59 UTC, jmperezra commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:layout_below="@id/Relative_view_1"
Hay que fijarse en el nombre de los id: tienen un formato erróneo y su nombre no aporta semántica.

2021-11-14 11:00 UTC, tijanidian commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:id="@+id/appCompatImageView"
done

2021-11-14 11:01 UTC, tijanidian commented on app/src/main/res/layout/view_card_glovo_constraint.xml
> +        android:id="@+id/main_text"
done

2021-11-14 11:04 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:id="@+id/img3"
done

2021-11-14 11:09 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_2.xml
> +        android:layout_below="@id/Relative_view_1"
done

2021-11-14 11:09 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +            android:id="@+id/img_button5"
done

2021-11-14 11:09 UTC, tijanidian commented on app/src/main/res/layout/view_exercices_netflix_1.xml
> +        android:id="@+id/Relative_view_1"
done

2021-11-14 11:09 UTC, merged