Ejercicio de la unidad 3 alerts-Clonar cabezera texto app Plagrícola
tijanidian/PMDM-TIJANI pull request #5
Opened 2021-11-05 19:34 UTC by tijanidian

## Description

Ejercicio de la unidad 3 alerts copiar texto app Plagrícola
## Related Issue

not yeat
## How has this been tested?

not yeat
## Design UI

not yeat
## Screenshots or Video
![Captura_android](https://user-images.githubusercontent.com/73607974/140568399-21efb81e-f4f9-49ac-bb8d-174de7c46af8.PNG)

2021-11-12 19:32 UTC, tijanidian commented
Añadido la parte de alerts con recylerview
![alert](https://user-images.githubusercontent.com/73607974/141524411-648df7dc-b8cc-4a61-aa2d-9451fcaa6c99.PNG)

2021-11-18 10:35 UTC, JavierManc commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Al ser FileEntity un modelo sería mejor que lo llamases FileModel, así tendrías un "naming" parecido en ambas clases ;)

2021-11-18 10:37 UTC, JavierManc commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/presentation/AlertActivity.kt
> +    private val viewModel: AlertViewModel = AlertViewModel(GetAlertUseCase(AlertDataRepository()))
Podrías tabular el código para que quede más estético con (ctrl + l)

2021-11-18 10:40 UTC, JavierManc commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/presentation/AlertActivity.kt
> +    private fun render() {
Este método podría estar en el AlertViewModel y así utilizar coroutines

2021-11-18 11:26 UTC, AlvaroLC reviewed
Te aconsejo que revises un par de comentarios que te deje para mejorar la calidad del código

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Podrías cambiar el naming de "FileEntity" por "FileModel", ya que se trata de un modelo.

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Podrías cambiar el naming de "FileEntity" por "FileModel", ya que se trata de un modelo.

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/SecondActivity.kt
> +class SecondActivity : AppCompatActivity() {
Deberías usar un naming más descriptivo para la clase "SecondActivity" como podría ser "AlertDetails"  😜

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/layout/activity_alerts.xml
> +            style="@style/main_text_plag"
El naming de los estilos debe ir con UpperCase, por ejemplo podrías poner "TitlePlag"

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +            android:layout_width="64dp"
Podrias crear un dimen para almacenar los valores fijos como ese "64dp"

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +                style="@style/main_text_plag"
El naming de los estilos debe ir con UpperCase, por ejemplo podrías poner "TitlePlag"

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +                style="@style/text_plag"
El naming de los estilos debe ir con UpperCase, por ejemplo podrías poner "SummaryPlag"

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/values/styles.xml
> +    <style name="text_plag">
El naming de los estilos debe ir con UpperCase, por ejemplo podrías poner "SummaryPlag"

2021-11-18 11:26 UTC, AlvaroLC commented on app/src/main/res/values/styles.xml
> +    <style name="main_text_plag">
El naming de los estilos debe ir con UpperCase, por ejemplo podrías poner "TitlePlag"

2021-11-18 11:33 UTC, JavierManc requested changes
Tienes algún error y algunas cosas que mejorar, comprueba los comentarios que te he dejado en el código :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/presentation/AlertActivity.kt
> +    private fun render() {
¿Seguro que el código funciona?, compruébalo ya que no utilizas ningún hilo ni para hacer la llamada a la API, ni para pintar en la vista. Podrías hacer un hilo que recoja las alertas, y otro que pinte las alertas en la UI. Pero es mejor que utilices Coroutine ;)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/AlertViewState.kt
> +class AlertViewState( val title:String, val date:String,val summary:String, val type:Int, val id:String) {
Te sobrarían los corchetes porque no agregas ningún método, además es mejor que lo pongas como data class :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/SecondActivity.kt
> +class SecondActivity : AppCompatActivity() {
El naming de SecondActivity no aporta nada, es mejor que lo llames por ejemplo AlertDetailsActivity

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/Ut02AlertRecyclerActivity.kt
> +        val alerts = viewModel.getALets()
No creas ningún hilo para hacer la llamada a la API, no creo que te funcione bien la actividad. Podrías crear un hilo ya sea aquí o en el ViewModel, aunque es mejor que uses coroutines ;)
Además podrías cambiar el naming de getALets a getAlerts

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/Ut02AlertRecyclerViewModel.kt
> +        val alerts = useCase.execute()
Crea un hilo o coroutine para que al ejecutar el caso de uso en la llamada a la API funcione correctamente :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/Ut02AlertRecyclerViewModel.kt
> +    fun getALets(): List<AlertViewState> {
Podrías mejorar el naming de getALets a por ejemplo getAlerts

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_users_example/presentation/UserViewState.kt
> +class UserViewState(val userId: Int, val fullName:String,val age:String) {
Te sobrarían los corchetes porque no agregas ningún método, además es mejor que lo pongas como data class :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_alerts.xml
> +    android:layout_margin="@dimen/margin_left"
El naming de este dimen no aporta información, si es un dimen que ajusta el margen de la cardview de la alerta, podrías llamarlo por ejemplo alert_card_margin

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_alerts.xml
> +            style="@style/main_text_plag"
Sería mejor si no abreviases  los naming de los id para que fueran más fáciles de entender. Por ejemplo si quieres referirte a las alertas como plaga, este id podría ser por ejemplo plague_main_text. 😄
Esto te ocurre en todos los naming referidos a las plagas, compruébalos.

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_alerts.xml
> +            android:id="@+id/date_published"
El naming no está mal pero podría mejorar para que fuese más fácil de entender, por ejemplo lo podrías llamar plague_date_published

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_alerts.xml
> +            android:id="@+id/summary"
El naming no está mal pero podría mejorar para que fuese más fácil de entender, por ejemplo lo podrías llamar plague_summary

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_ui_test_glovo.xml
> +        android:id="@+id/text_principal_marca"
¿Por qué esta esta vista en la PR de alertas?, no deberías meter archivos de actividades en las PR de otras actividades. 😄

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/activity_ut02_alert_recycler.xml
> +        android:id="@+id/rycler_example"
recycler_example no es un buen naming, podrías llamarlo alert_wrap_content, u otro nombre más acorde al ejercicio

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +    android:layout_margin="@dimen/margin_left"
El naming de este dimen no aporta información, si es un dimen que ajusta el margen de la cardview de la alerta, podrías llamarlo por ejemplo alert_card_margin

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +    <androidx.appcompat.widget.LinearLayoutCompat
No está mal que hayas usado un LinearLayout, pero podrías probar a usar un ConstraintLayout y comprobar si te resulta más sencillo de maquetar la vista 😄

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +            android:layout_height="64dp"
Podrías crear un dimen para el tamaño de la imagen y así usarlo tanto en el width como en el height. :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +                android:text="Nombre" />
Este texto sería mejor que lo metieses en un string :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +                android:text="Age" />
Este texto sería mejor que lo metieses en un string :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +    android:layout_margin="@dimen/margin_left"
El naming de este dimen no aporta información, si es un dimen que ajusta el margen de la cardview de la alerta, podrías llamarlo por ejemplo alert_card_margin

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +    <androidx.appcompat.widget.LinearLayoutCompat
No está mal que hayas usado un LinearLayout, pero podrías probar a usar un ConstraintLayout y comprobar si te resulta más sencillo de maquetar la vista 😄

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +            android:id="@+id/avatar"
Este no es un buen naming para el id, al ser el icono de la vista podrías llamarlo alert_icon o algo similar :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
Esta es el tercer layout que introduces, podría haber una manera de hacerlo sin introducir tantas capas, prueba con un ConstraintLayout ;)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/values/dimens.xml
> +    <dimen name="icon_height">32dp</dimen>
icon_height, icon_widht, icon_widht_medium y icon_height_medium tienen el mismo tamaño, podrías poner un único dimen que englobase todos ellos, como por ejemplo un icon_size o algo parecido :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/values/dimens.xml
> +    <dimen name="icon_width">32dp</dimen>
icon_height, icon_widht, icon_widht_medium y icon_height_medium tienen el mismo tamaño, podrías poner un único dimen que englobase todos ellos, como por ejemplo un icon_size o algo parecido :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/values/dimens.xml
> +    <dimen name="icon_width_medium">32dp</dimen>
icon_height, icon_widht, icon_widht_medium y icon_height_medium tienen el mismo tamaño, podrías poner un único dimen que englobase todos ellos, como por ejemplo un icon_size o algo parecido :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/values/dimens.xml
> +    <dimen name="icon_height_medium">32dp</dimen>
icon_height, icon_widht, icon_widht_medium y icon_height_medium tienen el mismo tamaño, podrías poner un único dimen que englobase todos ellos, como por ejemplo un icon_size o algo parecido :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/res/values/dimens.xml
>      <dimen name="icon_height_small">20sp</dimen>
icon_widht_small y icon_height_small tienen el mismo tamaño, podrías poner un único dimen que los englobase, como por ejemplo un icon_small_size o algo parecido :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/data/AlertDataRepository.kt
> +    override fun getALlAlerts(): List<AlertModel> {
Esta función debería devolver un listado de alertas recogido de una API en vez de crearla tu mismo :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Sería mejor que llamases al modelo de archivos FileModel en vez de FileEntity para seguir un patrón en los naming :)

2021-11-18 11:33 UTC, JavierManc commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/data/AlertDataRepository.kt
> +    override fun getALlAlerts(): List<AlertModel> {
Esta función debería devolver un listado de alertas recogido de una API en vez de crearla tu mismo :)

2021-11-18 11:36 UTC, tijanidian commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
solved

2021-11-18 11:38 UTC, tijanidian commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/presentation/AlertActivity.kt
> +    private val viewModel: AlertViewModel = AlertViewModel(GetAlertUseCase(AlertDataRepository()))
¡Buen consejo!

2021-11-18 11:39 UTC, tijanidian commented on app/src/main/java/com/tijanidian/alerts_with_mvvm/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Ya lo he resuelto, pero gracias :)

2021-11-18 11:41 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/SecondActivity.kt
> +class SecondActivity : AppCompatActivity() {
No me había fijado :)

2021-11-18 11:43 UTC, tijanidian commented on app/src/main/res/layout/view_item_ut02_ex02.xml
> +            android:layout_width="64dp"
Resuelto, le he metido un style al icono :)

2021-11-18 11:48 UTC, tijanidian commented on app/src/main/res/layout/activity_alerts.xml
> +            style="@style/main_text_plag"
Cierto es, creo que te refieres  CamelCase y no a UpperCase 👍

2021-11-18 11:50 UTC, tijanidian commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +                style="@style/main_text_plag"
done

2021-11-18 11:50 UTC, tijanidian commented on app/src/main/res/layout/view_item_ut02_recycler.xml
> +                style="@style/text_plag"
done

2021-11-18 11:51 UTC, tijanidian commented on app/src/main/res/values/styles.xml
> +    <style name="text_plag">
done

2021-11-18 11:51 UTC, tijanidian commented on app/src/main/res/values/styles.xml
> +    <style name="main_text_plag">
done

2021-11-18 11:53 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/SecondActivity.kt
> +class SecondActivity : AppCompatActivity() {
done

2021-11-18 11:58 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/AlertViewState.kt
> +class AlertViewState( val title:String, val date:String,val summary:String, val type:Int, val id:String) {
He probado la actividad de AlertActivity y funciona correctamente, y he cambiado el AlertViewState de una clase a un data class quitando los corchetes 💯

2021-11-18 12:02 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/Ut02AlertRecyclerActivity.kt
> +        val alerts = viewModel.getALets()
Resuelto

2021-11-18 12:11 UTC, tijanidian commented on app/src/main/res/values/dimens.xml
> +    <dimen name="icon_height_medium">32dp</dimen>
Buen consejo

2021-11-18 12:11 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/data/AlertDataRepository.kt
> +    override fun getALlAlerts(): List<AlertModel> {
Buena idea

2021-11-18 12:11 UTC, tijanidian commented on app/src/main/res/values/dimens.xml
>      <dimen name="icon_height_small">20sp</dimen>
buena idea

2021-11-18 12:14 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/data/AlertDataRepository.kt
> +    override fun getALlAlerts(): List<AlertModel> {
Resolví este problema sin utilizar retrofit2, porque no eran ámbito de este modulo, pero gracias por el consejo :)

2021-11-18 12:15 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/data/AlertDataRepository.kt
> +    override fun getALlAlerts(): List<AlertModel> {
Resolví este problema sin utilizar retrofit2, porque no eran ámbito de este modulo, pero gracias por el consejo :)

2021-11-18 12:16 UTC, tijanidian commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/domain/AlertModel.kt
> +data class FileEntity(val name: String, val url: String)
Bien visto, ¡gracias!

2021-12-02 15:43 UTC, jmperezra approved these changes
Cosas que esperaba ver:
- Coroutine
- LiveData
Muy interesantes los comentarios propuestos y las respuestas dadas.

Puedes hacer el merge.

2021-12-02 15:43 UTC, jmperezra commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/domain/AlertRepository.kt
> +    fun getALlAlerts():List<AlertModel>
Error de ortografía.

2021-12-02 15:43 UTC, jmperezra commented on app/src/main/java/com/tijanidian/ex02_alerts_recyclerview/presentation/Ut02AlertRecyclerActivity.kt
> +    private fun alertsWithRecyclerView() {
Cuidado con los nombres de las funciones, no refleja realmente lo que hace la función. Propuesta: loadAlerts

2021-12-02 16:51 UTC, merged